CONFIGPATH=$HOME/.config/zsh
mkdir -p $CONFIGPATH

# Aliases
alias grep="grep --color"
alias ls="exa -la --group-directories-first"
alias tree="exa -Ta --group-directories-first"

# Plugins
source <(antibody init)
antibody bundle <<EOBUNDLES
    denysdovhan/spaceship-prompt
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-completions
EOBUNDLES

# Options
setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks # remove superfluous blanks from history items
setopt inc_append_history # save history entries as soon as they are entered
setopt share_history # share history between different instances of the shell
setopt auto_cd # cd by typing directory name if it's not a command
setopt auto_list # automatically list choices on ambiguous completion
setopt auto_menu # automatically use menu completion
setopt always_to_end # move cursor to end if word had one match

# Path
export PATH=$HOME/.local/bin:$PATH

# Spaceship prompt options
SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  exec_time     # Execution time
  line_sep      # Line break
  jobs          # Background jobs indicator
  char          # Prompt character
)
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_TRUNC_PREFIX=.../

# History
HISTFILE=$CONFIGPATH/histfile
HISTSIZE=1000
SAVEHIST=1000

# Completion
zstyle :compinstall filename '/home/alexandre/.zshrc'
autoload -Uz compinit
compinit -d $CONFIGPATH/zcompdump

zstyle ':completion:*' menu select # select completions with arrow keys
#zstyle ':completion:*' group-name '' # group results by category
#zstyle ':completion:::::' completer _expand _complete _ignored _approximate # enable approximate matches for completion

# Bindkey
bindkey "^[[H"   beginning-of-line
bindkey "^[[F"   end-of-line
bindkey "^[[3~"  delete-char # https://blog.pilif.me/2004/10/21/delete-key-in-zsh/
bindkey "^[3;5~" delete-char # https://blog.pilif.me/2004/10/21/delete-key-in-zsh/

# Startx
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi

export XDG_CURRENT_DESKTOP=sway
